language: generic
os: linux
dist: trusty 
sudo: required
services: 
  - docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script:
  - docker-compose build
script:
- docker-compose up --detach


