version: "3.3"
services:
  pokemon-service:
    build: ./backend/pokemon
    ports:
      - "8000:8000"
  game-service:
    image: steven1schuerstedt/game-service
    build: ./backend/game
    ports:
      - "8001:8001"
  weather-service:
    build: ./backend/weather
    ports:
    - "8003:8003"
  frontend:
    image: steven1schuerstedt/frontend
    build: ./frontend/pokino-app
    ports:
      - "4200:80"


