language: generic
os: linux
dist: bionic

services:
  - docker

jobs:
  include:
    - stage: test
      name: "Backend/Game - Test"
      before_install:
        - cd backend/game
        - docker build -t game_image -f Dockerfile_CI .
        #- docker run -d -it --name frontend_ci frontend_image
     # script:
      #  - |
       #   docker exec -it frontend_ci /bin/sh -c "npm run test"
        