language: generic
os: linux
dist: bionic

services:
  - docker

jobs:
  include:
    - stage: test
      name: "CI - Test"
      before_install:
        - cd frontend/pokino-app
        - docker build -t frontend_image -f Dockerfile_test .
        #- docker run -d -it --name frontend_ci frontend_image
     # script:
      #  - |
       #   docker exec -it frontend_ci /bin/sh -c "npm run test"
        